# 🎵 Spotify EDA Project

## Data Cleaning & Preprocessing

### Objective
The goal of this notebook is to:
- load the Spotify dataset,
- inspect its structure,
- identify missing values,
- clean inconsistencies,
- and prepare the data for exploratory data analysis (EDA).

---

### Tools Used
- Pandas
- NumPy
- Matplotlib
- Seaborn

---

### Workflow
1. Import Libraries
2. Load Dataset
3. Initial Data Inspection
4. Missing Value Analysis
5. Duplicate Handling
6. Data Type Corrections
7. Save Cleaned Dataset

In [1]:
# =========================================
# IMPORTING REQUIRED LIBRARIES
# =========================================

# Data manipulation
import pandas as pd
import numpy as np

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Optional settings for better display
pd.set_option('display.max_columns', None)

print("Libraries Imported Successfully 🚀")

Libraries Imported Successfully 🚀

In [2]:
# =========================================
# DOWNLOADING SPOTIFY DATASET FROM KAGGLE
# =========================================

import kagglehub

# Download dataset
path = kagglehub.dataset_download(
    "maharshipandya/-spotify-tracks-dataset"
)

print("Dataset downloaded successfully ✅")
print("Dataset path:", path)

Dataset downloaded successfully ✅
Dataset path: C:\Users\Arpik\.cache\kagglehub\datasets\maharshipandya\-spotify-tracks-dataset\versions\1

In [3]:
# =========================================
# CHECK FILES INSIDE DOWNLOADED DATASET
# =========================================

import os

files = os.listdir(path)

print(files)

['dataset.csv']

In [4]:
# =========================================
# COPY DATASET INTO PROJECT RAW DATA FOLDER
# =========================================

import shutil
import os

# Source file path
source_file = os.path.join(path, files[0])

# Destination path
destination_file = "../data/raw/spotify.csv"

# Copy file
shutil.copy(source_file, destination_file)

print("Dataset copied successfully 🚀")

Dataset copied successfully 🚀

In [5]:
# =========================================
# LOAD DATASET
# =========================================

df = pd.read_csv("../data/raw/spotify.csv")

print("Dataset Loaded Successfully ✅")

Dataset Loaded Successfully ✅

In [6]:
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

# 📊 Dataset Shape

This step helps us understand:
- how many rows are present,
- how many columns/features exist in the dataset.

In [7]:
# =========================================
# CHECK DATASET SHAPE
# =========================================

print("Dataset Shape:", df.shape)

Dataset Shape: (114000, 21)

# 🏷️ Column Names

Understanding available features in the dataset.

In [8]:
# =========================================
# DISPLAY COLUMN NAMES
# =========================================

df.columns

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='str')

# ❓ Missing Value Analysis

Checking whether any columns contain null/missing values.

In [9]:
# =========================================
# CHECK MISSING VALUES
# =========================================

missing_values = df.isnull().sum()

missing_values

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [10]:
# =========================================
# DISPLAY ONLY COLUMNS WITH MISSING VALUES
# =========================================

missing_values = df.isnull().sum()

missing_values[missing_values > 0]

artists       1
album_name    1
track_name    1
dtype: int64

# 🔁 Duplicate Record Analysis

Identifying duplicate rows in the dataset.

In [11]:
# =========================================
# CHECK DUPLICATE ROWS
# =========================================

duplicate_count = df.duplicated().sum()

print("Total Duplicate Rows:", duplicate_count)

Total Duplicate Rows: 0

# 📈 Statistical Summary

Generating summary statistics for numerical columns.

In [12]:
# =========================================
# SUMMARY STATISTICS
# =========================================

df.describe()

,Unnamed: 0,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,56999.500000,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,32909.109681,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28499.750000,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,56999.500000,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,85499.250000,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,113999.000000,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [13]:
# =========================================
# CHECK DATA TYPES
# =========================================

df.dtypes

Unnamed: 0            int64
track_id                str
artists                 str
album_name              str
track_name              str
popularity            int64
duration_ms           int64
explicit               bool
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature        int64
track_genre             str
dtype: object

# 🧹 Removing Unnecessary Columns

The column `Unnamed: 0` appears to be an automatically generated index column and does not contribute to analysis.

It will be removed to keep the dataset clean and efficient.

In [14]:
# =========================================
# REMOVE UNNECESSARY COLUMN
# =========================================

df.drop(columns=['Unnamed: 0'], inplace=True)

print("Column Removed Successfully ✅")

Column Removed Successfully ✅

In [15]:
df.columns

Index(['track_id', 'artists', 'album_name', 'track_name', 'popularity',
       'duration_ms', 'explicit', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'time_signature', 'track_genre'],
      dtype='str')

# 🏷️ Feature Categorization

Separating numerical and categorical columns for easier exploratory data analysis.# 🏷️ Feature Categorization

Separating numerical and categorical columns for easier exploratory data analysis.

In [16]:
# =========================================
# IDENTIFY NUMERICAL COLUMNS
# =========================================

numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns

print("Numerical Columns:\n")
print(numerical_columns)

Numerical Columns:

Index(['popularity', 'duration_ms', 'danceability', 'energy', 'key',
       'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness',
       'liveness', 'valence', 'tempo', 'time_signature'],
      dtype='str')

In [17]:
# =========================================
# IDENTIFY CATEGORICAL COLUMNS
# =========================================

categorical_columns = df.select_dtypes(
    include=['object', 'string', 'bool']
).columns

print("Categorical Columns:\n")
print(categorical_columns)

Categorical Columns:

Index(['track_id', 'artists', 'album_name', 'track_name', 'explicit',
       'track_genre'],
      dtype='str')

In [18]:
# =========================================
# SAVE CLEANED DATASET
# =========================================

df.to_csv("../data/cleaned/spotify_cleaned.csv", index=False)

print("Cleaned dataset saved successfully ✅")

Cleaned dataset saved successfully ✅